<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Areas\Administrator\Data\**" />
    <Compile Remove="Areas\Administrator\Models\**" />
    <Content Remove="Areas\Administrator\Data\**" />
    <Content Remove="Areas\Administrator\Models\**" />
    <EmbeddedResource Remove="Areas\Administrator\Data\**" />
    <EmbeddedResource Remove="Areas\Administrator\Models\**" />
    <None Remove="Areas\Administrator\Data\**" />
    <None Remove="Areas\Administrator\Models\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CineVerse.Infrastructure\CineVerse.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
